name: Build C# EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Create project
        run: dotnet new console -n choke

      - name: Replace Program.cs
        run: copy cs\choke.cs choke\Program.cs

      - name: Publish EXE
        run: dotnet publish choke -c Release -r win-x64 --self-contained true

      - name: Create Release and Upload EXE
        uses: softprops/action-gh-release@v2
        with:
          files: choke/bin/Release/net8.0/win-x64/publish/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
